### ISSUE TITLE
Night Mode

### ISSUE THREAD

**Issue by DeltaManiac** [rust-community/rust-lang-blog-boilerplate#3]
Is there a night mode/dark variant?

**Comment by o0Ignition0o** [comment]
Hi and welcome to the project :)
There isn't any night mode yet, but that sounds like a good idea.
If you find one or create your own, please let me know !

**Comment by DeltaManiac** [comment]
I dont know much about CSS but I Fiddled around with the [ayu-rs](https://github.com/Cldfire/ayu-rs/blob/master/css/twir.css) theme for this-week-in-rust and it supports night mode for this blog template with a small change.
```css
.highlight {
    background-color:#191f26
}

pre,code {
        background-color:#191f26
}

#site-logo {
        filter: invert(100%);
}
```

Just stick the above code to the end and Voila!😎

![Landing Page](https://user-images.githubusercontent.com/3689561/42558203-2c4aef80-850e-11e8-9874-aab26c3b0b7b.png)


![Post](https://user-images.githubusercontent.com/3689561/42558176-123a94ec-850e-11e8-8e02-497011c05c38.png)
